# Copied and modified from yamls/module3_flow/reco/light/LightADC64EventGenerator.yaml

classname: LightADC64EventGenerator
path: proto_nd_flow.reco.light.adc64_event_generator-single_module
dset_name: 'light/events'
params:
  # secondary output
  wvfm_dset_name: 'light/wvfm'

  # configuration parameters
  n_adcs: 2
  n_channels: 64
  sn_table:
   - 215553019 # ACL
   - 215563696 # LCM
  sync_channel: 32
  sync_threshold: 10000
  batch_size: 128
  utime_ms_window: 1000
  tai_ns_window: 1000
