classname: LightADC64EventGenerator
path: proto_nd_flow.reco.light.adc64_event_generator
dset_name: 'light/events'
params:
  # secondary output
  wvfm_dset_name: 'light/wvfm'

  # configuration parameters
  n_adcs: 8
  n_channels: 64
  sn_table:
   - 215564600  # Mod0, Slot 3
   - 215537224  # Mod0, Slot 5
   - 642823167  # Mod1, Slot 7
   - 215553019  # Mod1, Slot 9
   - 215564617  # Mod2, Slot 11
   - 642874879  # Mod2, Slot 13
   - 642504959  # Mod3, Slot 15
   - 632779263  # Mod3, Slot 17
  sync_channel: 0
  sync_threshold: 40000
  batch_size: 12
  utime_ms_window: 1000
  tai_ns_window: 1000
