classname: LightMPDEventGenerator
path: proto_nd_flow.reco.light.mpd_event_generator
dset_name: 'light/events'
params:
  # secondary output
  wvfm_dset_name: 'light/wvfm'

  # configuration parameters
  n_adcs: 4
  n_channels: 64
  sn_table:
   - '0x0e7550ee'  # TPC A, Side 0, Slot 19
   - '0x0cd13dd6'  # TPC A, Side 1, Slot 16
   - '0x0cd94149'  # TPC B, Side 0, Slot 12
   - '0x0cd9414a'  # TPC B, Side 1, Slot 8
  sync_channel: 0
  sync_threshold: 40000
  batch_size: 12
  utime_ms_window: 1000
  tai_ns_window: 1000
  rwm_channel: [0,18]
  rwm_threshold: 10000
